spring.application.name=love-certificate

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Jackson Configuration
spring.jackson.default-property-inclusion=non_null

# ====================================Love Certificate Configuration====================================

# OTP expiration time in seconds (default: 120 seconds = 2 minutes)
love.certificate.otp-expire-seconds=120

# Maximum number of OTP retry attempts (default: 5)
love.certificate.max-otp-retry=3

# OTP length in digits (default: 6)
love.certificate.otp-length=6
love.certificate.otp-salt-length=16
love.certificate.iterations=10000
love.certificate.key-length=256

love.certificate.connect-timeout-ms=30000
love.certificate.read-timeout-ms=30000

# Schedule
spring.task.scheduling.pool.size=2

# Runs every day at 9 AM
#scheduler.milestone.cron=0 0 9 * * ?
scheduler.milestone.enabled=true

scheduler.email-retry.enabled=true
scheduler.email-recovery.enabled=true

# batch size cho claim job
email.job.claim-limit=10
email.job.timeout-minutes=5

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=Love Certificate <your-email@gmail.com>

# Key path
local.private-key.path=keys/private_key.pem
local.public-key.path=keys/public_key.pem

# OTP client
sms.base-url=sethemsau
sms.url.send-otp=user
sms.environment=TEST


